### ISSUE TITLE
Unable to run tests due to missing ts-node

### ISSUE THREAD

**Issue by lyqht** [kbysiec/vite-vanilla-ts-lib-starter#3]
When I tried running tests with 
```
npm test -- ts-node
```

I get the following error

```
Error: Jest: Failed to parse the TypeScript config file /Users/lyqht/self-study/vite-vanilla-ts-starter/jest.config.ts
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find module 'ts-node'
Require stack:
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-config@27.5.1/node_modules/jest-config/build/readConfigFileAndSetRootDir.js
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-config@27.5.1/node_modules/jest-config/build/index.js
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-cli@27.5.1/node_modules/jest-cli/build/init/index.js
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-cli@27.5.1/node_modules/jest-cli/build/cli/index.js
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-cli@27.5.1/node_modules/jest-cli/build/index.js
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-cli@27.5.1/node_modules/jest-cli/bin/jest.js
- /Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest@27.5.1/node_modules/jest/bin/jest.js
    at readConfigFileAndSetRootDir (/Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-config@27.5.1/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
    at async readConfig (/Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-config@27.5.1/node_modules/jest-config/build/index.js:233:18)
    at async readConfigs (/Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-config@27.5.1/node_modules/jest-config/build/index.js:420:26)
    at async runCLI (/Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/@jest+core@27.5.1/node_modules/@jest/core/build/cli/index.js:132:59)
    at async Object.run (/Users/lyqht/self-study/vite-vanilla-ts-starter/node_modules/.pnpm/jest-cli@27.5.1/node_modules/jest-cli/build/cli/index.js:155:37)
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by kbysiec** [comment]
I updated the template with the newest packages versions. Additionally I added ts-node package. Now everything should work. 

Regards,
Kamil
